version: '3'
services:
  nginx:
    build: .
    networks:
      - govuk
    ports:
      - 80:80
  frontend:
    image: frontend
    env_file: ./envfile
    networks:
      - govuk
    external_links:
      - shared_content-store_1
  static:
    image: static
    env_file: ./envfile
    networks:
      - govuk


networks:
  govuk:
    external:
      name: shared_govuk
