version: '3'
services:
  nginx:
    build: ./publisher
    networks:
      - govuk
    ports:
      - 80:80
  calculators:
    image: calculators
    env_file: ./publisher/govuk-envfile
    networks:
      - govuk
  calendars:
    image: calendars
    env_file: ./publisher/govuk-envfile
    networks:
      - govuk
  publisher:
    image: publisher
    env_file: ./publisher/govuk-envfile
    external_links:
      - shared_postgres_1
      - shared_rabbitmq_1
      - shared_content-store_1
    networks:
      - govuk
  publishing-api:
    image: publishing-api
    env_file: ./publisher/govuk-envfile
    external_links:
      - shared_postgres_1
      - shared_rabbitmq_1
      - shared_content-store_1
    networks:
      - govuk
  static:
    image: static
    env_file: ./publisher/govuk-envfile
    networks:
      - govuk

  redis:
    image: redis
    hostname: redis
    networks:
      - govuk
  mongo:
    image: mongo
    hostname: mongo
    volumes:
      - "mongo-data:/data/db"
    networks:
      - govuk
  rabbitmq:
    image: rabbitmq
    env_file: ./shared/rabbitmq-envfile
    hostname: rabbitmq-shared
    volumes:
      - "rabbitmq-data:/var/lib/rabbitmq"
    networks:
      - govuk
  postgres:
    image: postgres
    env_file: ./shared/postgres-envfile
    hostname: postgres
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    networks:
      - govuk
  content-store:
    image: content-store
    hostname: content-store
    networks:
      - govuk

volumes:
  mongo-data:
  postgres-data:
  rabbitmq-data:

networks:
  govuk:
