version: '3'
services:
  calculators:
    build: gds-services/calculators
    hostname: calculators
    env_file: ./services/govuk-env
    networks:
      - govuk
  calendars:
    build: gds-services/calendars
    hostname: calendars
    env_file: ./services/govuk-env
    networks:
      - govuk
  content-store:
    build: gds-services/content-store
    hostname: content-store
    networks:
      - govuk
  content-tagger:
    build: gds-services/content-tagger
    env_file: ./services/govuk-env
    hostname: content-tagger
    networks:
      - govuk
    ports:
      - 3116:3116
  frontend:
    build: gds-services/frontend
    env_file: ./services/govuk-env
    networks:
      - govuk
  publisher:
    build: gds-services/publisher
    env_file: ./services/govuk-env
    networks:
      - govuk
  content-publisher:
    build: gds-services/content-publisher
    env_file: ./services/govuk-env
    networks:
      - govuk
    ports:
      - 3221:3221
  publishing-api:
    build:
      context: gds-services/publishing-api
      dockerfile: ../../services/publishing-api/Dockerfile
    env_file: ./services/govuk-env
    networks:
      - govuk
  static:
    build: gds-services/static
    env_file: ./services/govuk-env
    hostname: static
    networks:
      - govuk
    ports:
      - 3013:3013

  mongo:
    image: mongo
    hostname: mongo
    volumes:
      - "mongo-data:/data/db"
    networks:
      - govuk
  nginx:
    build: services/nginx
    networks:
      - govuk
    ports:
      - 80:80
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
      POSTGRES_DB:
    hostname: postgres
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    networks:
      - govuk
  rabbitmq:
    image: rabbitmq
    environment:
      RABBITMQ_HOSTS: rabbitmq
      RABBITMQ_DEFAULT_USER: publishing_api
      RABBITMQ_DEFAULT_PASS: publishing_api
    hostname: rabbitmq
    volumes:
      - "rabbitmq-data:/var/lib/rabbitmq"
    networks:
      - govuk
  redis:
    image: redis
    hostname: redis
    networks:
      - govuk

volumes:
  mongo-data:
  postgres-data:
  rabbitmq-data:

networks:
  govuk:
