version: '3'
services:
  nginx:
    build: .
    networks:
      - govuk
    ports:
      - 80:80
  calculators:
    image: calculators
    env_file: ./govuk-envfile
    networks:
      - govuk
  calendars:
    image: calendars
    env_file: ./govuk-envfile
    networks:
      - govuk
  publisher:
    image: publisher
    env_file: ./govuk-envfile
    external_links:
      - shared_postgres_1
      - shared_rabbitmq_1
      - shared_content-store_1
    networks:
      - govuk
  publishing-api:
    image: publishing-api
    env_file: ./govuk-envfile
    external_links:
      - shared_postgres_1
      - shared_rabbitmq_1
      - shared_content-store_1
    networks:
      - govuk
  static:
    image: static
    env_file: ./govuk-envfile
    networks:
      - govuk

volumes:
  mongo-data:
    external:
      name: shared_mongo-data
  postgres-data:
    external:
      name: shared_postgres-data
  rabbitmq-data:
    external:
      name: shared_rabbitmq-data

networks:
  govuk:
    external:
      name: shared_govuk
