version: '3'
services:
  redis:
    image: redis
    hostname: redis
    networks:
      - govuk
  mongo:
    image: mongo
    hostname: mongo
    volumes:
      - "mongo-data:/data/db"
    networks:
      - govuk
  rabbitmq:
    image: rabbitmq
    env_file: ./rabbitmq-envfile
    hostname: rabbitmq-shared
    volumes:
      - "rabbitmq-data:/var/lib/rabbitmq"
    networks:
      - govuk
  postgres:
    image: postgres
    env_file: ./postgres-envfile
    hostname: postgres
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    networks:
      - govuk
  content-store:
    image: content-store
    hostname: content-store
    networks:
      - govuk

volumes:
  mongo-data:
    external:
      name: shared_mongo-data
  postgres-data:
    external:
      name: shared_postgres-data
  rabbitmq-data:
    external:
      name: shared_rabbitmq-data

networks:
  govuk:
    external:
      name: shared_govuk
